 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/spotify_searches", type: :request do
  
  # SpotifySearch. As you add validations to SpotifySearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SpotifySearch.create! valid_attributes
      get spotify_searches_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SpotifySearch" do
        expect {
          post spotify_searches_url, params: { spotify_search: valid_attributes }
        }.to change(SpotifySearch, :count).by(1)
      end

      it "redirects to the created spotify_search" do
        post spotify_searches_url, params: { spotify_search: valid_attributes }
        expect(response).to redirect_to(spotify_search_url(SpotifySearch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SpotifySearch" do
        expect {
          post spotify_searches_url, params: { spotify_search: invalid_attributes }
        }.to change(SpotifySearch, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post spotify_searches_url, params: { spotify_search: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested spotify_search" do
      spotify_search = SpotifySearch.create! valid_attributes
      expect {
        delete spotify_search_url(spotify_search)
      }.to change(SpotifySearch, :count).by(-1)
    end

    it "redirects to the spotify_searches list" do
      spotify_search = SpotifySearch.create! valid_attributes
      delete spotify_search_url(spotify_search)
      expect(response).to redirect_to(spotify_searches_url)
    end
  end
end
